config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,:email,:password,presence: true
  before_create :expire_time_create
  def cron_job
    User.where(self.created_at+10.minutes=self.expire_time_user).destroy_all
  end
  private
  def expire_time_create
    self.expire_time_user=self.created_at.to_datetime+10.minutes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user=User.find(params[:id])
  end
  def new
    @user=User.new
  end
  def create
    @user = User.new(user_params)
        
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end
  def edit
    @user=User.find(params[:id])
  end
  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end
  def destroy
    @user=User.find(params[:id])
    @user.destroy
    flash[:info]= 'user successful delete'
    redirect_to users_path
  end
  private
    def user_params
      params.require(:user).permit(:name,:email,:password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="container marTop100">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <%= form_for @user do |f|%>

        <div class="form-group">
          <label for="name">Name</label>
          <%= f.text_field :name, placeholder: "Enter Name",class: "form-control"%>
        </div>
          <div class="form-group ">
            <label for="email">Email</label>
            <%= f.email_field :email, placeholder: "Enter Your Email",class: "form-control"%>
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <%= f.password_field :password, placeholder: "Enter Password",class: "form-control"%>
          </div>
          <div class="form-group">
                <%= f.submit class: "btn btn-primary", value: "Submit" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="col-lg-8 col-lg-offset-2">
  <div class="pull-right marTop20 ">
    <%= active_link_to "Add New User", new_user_path,class:"btn btn-primary" %>
  </div>
  <% flash.each do |name,msg| %>
      <b><%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert alert-success col-lg-12" %></b>
  <% end %>
  <table class="table marTop100">
    <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Create At</th>
      <th>Expire Time</th>
      <th colspan="2">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.expire_time_user %></td>
        <td><%= active_link_to "Show", user_path(user) %></td>
        <td><%= active_link_to "Edit", edit_user_path(user) %></td>
        <td><%= active_link_to "Delete", user_path(user) ,method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<table class="table table-bordered marTop100">
  <tr>
    <th>Name</th>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= @user.email %></td>
  </tr>

</table>